name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f49b25f3c7a80ad6d62d4dabc87ab5cfd8b567274351e916c5f29dc8c912699a"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
