name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d42721c2ea215668c3e5fd098dbfa959c267fc4a321c69470fae77877b68895"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
