name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c210c20011a3c9de7f0fcc54630c1b32a2fff626f8292a4e7d6f1dd730f747b8"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
