name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "400df60282c03c1f8b5b41e6ec6eea9e6ac1744d2a70b4102e92e38016acd74b"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
