name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44d880ceb7e7c1c3d4ab60a95a4910c69c1b6508443f7991cc22c43b8bc0d8dc"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
