name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d73c5186bbf16ea919f1efbaa7b89b2388bbb9880c6abea1374159d6830e64a9"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
