name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cefeefb66c9f6c6846bd012cd563d54655287dd506a9aacf495ae5e17303466"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
