name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d1a8fa79da82f4bf8ca87a15e4f633fff1da123a42fb64087e1d1c82c1e1b5f"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
