name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac242b31b7cff025e5b1fbe92e3ab29b713ea8a1e6e0f245d23cbe705e9c1013"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
