name = "WHOSMP"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80ed742bd1d0cd400a3243f94e88c721f2cf2b235b857f7a1672c6df605d11d9"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
