name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a50b019a9f1c2f84a8d01fdbcbd89ce301cdb3b9bdebcf992ad8db82208e1a70"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
