name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2c43b1310a118624acfa68c7daff9b0ce1f6a78b5e1e4645f1ac6136104c50b"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
