name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea10af943c59fa484a09171e67db6d6ea7e47bbd9feb081ef57fe2f9e93fe0a9"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
