name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4c80fddff63405bb692962af241cec33e747e03e134fea8b5f6d9127f741bcb"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
