name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64b95d3be8d66d6aad2d81c26167c4cbef5f4bb3edc85a1b386478a1b44fe1f0"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
