name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b48d31d3f6ef3a0f5787c82f807a67604c5a084762a27825f271ec4529b6ec6"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
