name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd9e42fc6a413cca7a3570ab0a6ecc0548209c363ab7aeb8ffbec256b703e279"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
