name = "WHOSMP"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a09dc135240f08805034eafeae7d8f60575cfc1736d65af56df2126f0c4584f"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
