name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d83517906c961402a0b11a00977b45527192acc72e6a41a65ed7ff7cf4d8be48"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
