name = "WHOSMP"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "984136382c08ad1828ed3d84fed220cef4095d626678e5f51db19333a93a2db9"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
