name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1414a8cd2b6813ddbf8d2b0ad3a7cdd4a3dcad698b122343cec9ac08f0efc63"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
