name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3f5f60ac1be02db781d62f5f788642294b98bc02e1b3377687af19cb7af5344"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
