name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71a3e6b11e6f1e38709ef766d09f569268b41e9e89940aeccc73ab9bb7d57f3b"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
