name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aa014bb874496b6378de4f5ce7acb53f2fa89c2a36f162dc07ff7d034bc5187"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
