name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "509f9c28e8e9331d005e2492eb594d63575d7c9256a452a1a805dc49f6ee0ee9"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
