name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d264b14edfb7d9127e80bdeb7bba3bd29df2ab3672d0b00a3ffa980d8c76d59"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
