name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1c931c932ac47cbd628a1fd0b791504391f958e151cc3f636eb5e2e0e008798"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
