name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30407d8e52e2605b349129d36bac661c2164b5ddfd0fcc1b987856e08ab82813"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
