name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aad94ea7634036842b1f98b2dbe259c5f357191cb5c4592162bddfb90ada386"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
