name = "WHOSMP"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69c2ad8b856c0202da541a842ae98f0d1d011675a2400d6c375b6682997be547"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
