name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59406dd47593dba3d6e0dd98019ed5e0fed0694cc41862385311e8e1f8c2d0fc"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
