name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98c83599eb8076c65714d9699aab84dab5a8eb94c0eb162bf9fb55c9cb773204"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
