name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d8d3c4489801fbd5c1ebde721d38522b2a58de9dfa92d57eca85beeb93dc8d4"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
