name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89dec637bed7c2ccc124fcb3a801b4cccac315e741d5a79061e04b38a8f9eed8"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
