name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca2ba55fbf30e2b254b5e0e0921f9a6e8ad09579a7a6fd54606cbf01894bf92e"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
