name = "WHOSMP"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "477f834d6af52d28673566e57a222f7cf95ed3bd67086a506c52670a2fa1ff98"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
