name = "DNDBois Pokemon"
author = "Nocturne705"
version = "1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ddc3b9bed88f0cca264ab5cecd2aa0ca19faf37b699a1e18c7d3f2dce73e16c"

[versions]
forge = "36.2.30"
minecraft = "1.16.5"
