name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f3481d445b71da200ed251fc1179caddd32d6c10958b38bbfbcda62c23aa29b"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
