name = "WHOSMP"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9c7b7de96b311d2d4a10feaa6d030b06eed81ba2238af10801efa268a17b50e"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
