name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62415c043c81ede1e52eb411123add09e6d6881e5d4a76e750b0928a807719bc"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
