name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7a7f70191ac1994470a0365bc04e1a612fb1675b25fcbfaf12fe6a5390e3178"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
