name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "383c753b64fa0add34a41b97cf1f1dd31dc51e4501df8e9372cc078ea0177f8a"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
