name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac4943c76224ddb7381d7fb0a8c39f57929f7fec802e682a30da9802581c307e"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
