name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d67222401de6cd198edf04c271ce76568112f95e82545ce7fd3420f5ef378233"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
