name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32fa9bd79f7a3e4a3cec52fccecbfaa46d17d578f4322f0a315167acf5369c65"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
