name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3204b44a4a8820a591c7d935e8308a6cb150f8666d23503bab1ff4590f933a5f"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
