name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b65afb4cd66a2e794cb4ada204d015af7d1747370b592273059d66a2fa2fb71"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
