name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67de46270d3f56498beeda2fead24c06b377f6e7b13533a3d610eb19b6c5f9f6"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
