name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68278f6c30cb140eec463c8b1c60e68d743e67def82df08693145e6e0e48b9b2"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
