name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7628b5ca15dcb5f1a0db1219b3a2163985c2d009c058810eb2e42e908e9ba653"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
