name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e11df9d3ec8c9289e91ba7bd64052714f706e93e5595b04746c50fc3faf6450"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
