name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cf593f19fd76ecc8eb03e9477a4833662f8d0258d408073e72dac3352d0d573"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
