name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90e622fefdcd3f2f2d62764b46fd72d68d29de6268929c14b54abf326b902c55"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
