name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a502e7f071d2aadcf2dab523047d29cb579d163962712716c23eec10581404cc"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
