name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7e1956d67fbeaeeed6c0bc1f90ce5dbb3f1c632f3c1d0447d33f97a7418d664"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
