name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2095773d6c592e1367dc21c740ee70e84051e4ba5f6fe3cf39921adccb4f1b6a"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
