name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f29d169b684fd75ca2fd18475de3c8dac78d1b615ad827f52cee6def5b693315"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
