name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "559962e44d5b15c364e7c4df06cf740a6424fb556dbbec9c131139d17ce0a2a5"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
