name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f84a88bbd98cc8c487811c88054a5c36357f78d0dd847ce20ee68eca341e7ef"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
