name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c71571df54dcbe6e09680a67914911c12c3bdb96a10845226ba6e0f54eef50cd"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
