name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "946dfeed71dc84633a3cc73f64abc888b7d74633057699729d246cf61e9f893b"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
