name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eadf70a6855094a866595f5dbb48ddb7681dd3b757990ea3df9a678d17695996"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
