name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fff3a4905c87da1e6c4046c264b4fc61f371b29cf90e92e0de14200ae660a4dc"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
