name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21359438fcc00c43a5d3e45a919513cdd8e24b5c5ed39ad123684e32264e8eff"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
