name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbefe7bad6c79d93d9cc4f0b19a22e043dcbd3aea264d969a13d161f84d5d311"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
