name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f83143d4ef73579e8867e3262e785c4ad5c0c6c172f7580df82f3f0544fdd907"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
