name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0164d3c418c41d3dfa477a85dc8bea69edb245a432940be59a71631e16325c3d"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
