name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5c119fe5399e9234e47530372d7f4ef4dee37558c9f81f27d1358f56856e867"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
