name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "590a8d781bea3cdcdacb1ff8df487eeaa3d26dac76c0300129736386dd3a28ac"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
