name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "707ffb36df22dfdc6eecfc37a6cf68d102684248cc31aaec6284a3f9d8f8f069"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
