name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "925e3556cd33abcd60db509e602844b6a7fd15253b030157f237e877b9577bfe"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
