name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea0fe6f70183389b694ddd77dd951ca61d94b7dc095712d70f665bb7d292fcab"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
