name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39d92978ff52e09b472c5b6ea7ed0ad62d5a056cdecbd81ec7d7c79281fa450b"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
