name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67bf34c7621bcf2f6bc14d43d39ec8c3b688e56091e3d1d2c524f2e3f807adcc"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
