name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c03777197f91239bd1b50073ba583b8a90edcfe33b9856e23d5cb67b48bf690a"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
