name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd4ca6c1a3a4cc8f3769e5e1212794fdf902a1f15ce17b870dc5ce4ba1495e9c"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
