name = "Nocturnus2.0"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab1b212cde21738fa3dfef12e8d800bf8863892e0486c5cb0fff9dde6e999460"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
