name = "WHOSMP"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1c4886d9aa306384613b25b9a750080b6dbfc89b90f5420b59892888b10f229"

[versions]
forge = "39.1.2"
minecraft = "1.18.1"
