name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eba0f7487086db47627c6b6a035201d3e8ca2186fdf08c2645ce4df0ff2a35b3"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
