name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49bdecb11b2052c48201c8bb518ae45449bedfc92583a0cd5b2fc2414ff97eb7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
