name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6e3e452d1d810bbbfbc3b077115192ba412b3932c3d8579fc4f02a3d4f03e4d"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
