name = "Nocturnus20.1"
author = "Nocturne705"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64975b02b21c55f74c435cf4808a13f4682c72fcf8a586acdfd9515c2dcc8be3"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
