name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27b8f5e070dcbac24c37261144a1a4ca832058e0e4af23acc8b8ebf55444f8cc"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
