name = "Nocturnus"
author = "Nocturne705"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a05084f16d60e9dfeaef70e6c0b0cd8155a7a58daa078334580d7075c6198280"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
