name = "WHOSMP2"
author = "Nocturne705"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9d6be57a56ee3c02ed76e14a316d1b0feed168c2fbc328a8e37676881c03e0e"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
