
[client]
	# Position of the Wearables button. [Default: [27, 9]]
	buttonPos = [27, 9]
	# Enables the tooltip for the Wearables button. [Default: true]
	buttonTooltip = true
	# Enables the Wearables button. [Default: true]
	hasButton = true
	# Render blacklist for wearables.
	renderBlacklist = []

