
[Animals]

	[Animals.fox]
		"Taming Enabled" = true

	[Animals.rabbit]
		"Taming Enabled" = true

	[Animals.polar_bear]
		"Taming Enabled" = true

	[Animals.panda]
		"Taming Enabled" = true

	[Animals.ocelot]
		"Taming Enabled" = true

	[Animals.dolphin]
		"Taming Enabled" = true

	[Animals.wolf]
		"Taming Enabled" = true

	[Animals.cat]
		"Taming Enabled" = true

	[Animals.parrot]
		"Taming Enabled" = true

	[Animals.pig]
		"Taming Enabled" = true

	[Animals.sheep]
		"Taming Enabled" = true

	[Animals.cow]
		"Taming Enabled" = true

	[Animals.chicken]
		"Taming Enabled" = true

	[Animals.strider]
		"Taming Enabled" = true

	[Animals."Custom Mobs"]
		#[Registry Name, Tame Item, Protection, Requires Shift Click for State Change]
		"Animal List" = [["minecraft:chicken", "minecraft:wheat", "false", "false"]]

[Taming]
	"Multiple Items" = false
	"Vanilla Style Fox" = false

[Feedback]
	"Formatting Code" = "6l"

[Behaviours]
	"Fox Combat Enabled" = false
	"Tame Protection Enabled" = true

