name = "Bed Benefits"
filename = "BedBenefits-1.16.5-5.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/569/BedBenefits-1.16.5-5.0.4.jar"
hash-format = "sha1"
hash = "19aae3444d0e85da4cd3e1d4e1c305611333cd82"

[update]
[update.curseforge]
file-id = 3348569
project-id = 377051
