name = "Better Fps - Render Distance[Forge]"
filename = "betterfpsdist-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/461/betterfpsdist-1.1.jar"
hash-format = "sha1"
hash = "5f089dd5f0b266f3f449d195b7a42ed6b7539f9a"

[update]
[update.curseforge]
file-id = 3543461
project-id = 551520

[option]
default = true
description = "Performance and FPS improvement."
optional = true