name = "Better Title Screen"
filename = "BetterTitleScreen-1.16.4-1.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3111/817/BetterTitleScreen-1.16.4-1.10.2.jar"
hash-format = "sha1"
hash = "aecf62d254395e4068b6537e0563291f8e1a7e67"

[update]
[update.curseforge]
file-id = 3111817
project-id = 224223
