name = "Clef"
filename = "Clef-1.16.5-10.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3224/926/Clef-1.16.5-10.0.2.jar"
hash-format = "sha1"
hash = "09f2fc607e8d2224a8d974e50e869a9c11e10625"

[update]
[update.curseforge]
file-id = 3224926
project-id = 274783
