name = "CodeChicken Lib 1.8.+"
filename = "CodeChickenLib-1.16.5-4.0.7.444-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3658/104/CodeChickenLib-1.16.5-4.0.7.444-universal.jar"
hash-format = "sha1"
hash = "cf823cece16669cb4d46a12bbc308fc1cc70bf43"

[update]
[update.curseforge]
file-id = 3658104
project-id = 242818
