name = "Curios API (Forge)"
filename = "curios-forge-1.16.5-4.0.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/39/curios-forge-1.16.5-4.0.8.0.jar"
hash-format = "sha1"
hash = "14a6dfa711628d694582f7d54a7dca0fafcbab3a"

[update]
[update.curseforge]
file-id = 3613039
project-id = 309927
