name = "Distant Horizons: A Level of Detail mod"
filename = "DistantHorizons-1.6.2a-1.16.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3651/464/DistantHorizons-1.6.2a-1.16.5.jar"
hash-format = "sha1"
hash = "51db57e09f50704752cef9f12b117da41e49ce25"

[update]
[update.curseforge]
file-id = 3651464
project-id = 508933
