name = "Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons"
filename = "enhancedcelestials-2.0.9-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3532/22/enhancedcelestials-2.0.9-1.16.5.jar"
hash-format = "sha1"
hash = "26fc85165d24acd3390d563196cc0b44ed88c8b0"

[update]
[update.curseforge]
file-id = 3532022
project-id = 438447
