name = "GeckoLib"
filename = "geckolib-forge-1.16.5-3.0.65.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/666/geckolib-forge-1.16.5-3.0.65.jar"
hash-format = "sha1"
hash = "187b5e73747f1a0f1b2bd24a8e9cc31d5a997a5a"

[update]
[update.curseforge]
file-id = 3629666
project-id = 388172
