name = "GraveStone Mod"
filename = "gravestone-1.16.5-1.0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3447/911/gravestone-1.16.5-1.0.7.jar"
hash-format = "sha1"
hash = "adb3e1f6755c12d479e2a25d7ccd21b827814467"

[update]
[update.curseforge]
file-id = 3447911
project-id = 238551
