name = "JourneyMap"
filename = "journeymap-1.16.5-5.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3696/399/journeymap-1.16.5-5.8.0.jar"
hash-format = "sha1"
hash = "b4065dcd8d4237dfb1b6f1251ddd2dc8f7588e53"

[update]
[update.curseforge]
file-id = 3696399
project-id = 32274