name = "Macaw's Fences and Walls"
filename = "mcw-fences-1.0.3-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3682/815/mcw-fences-1.0.3-mc1.16.5.jar"
hash-format = "sha1"
hash = "9909220854db49863126010c4a221a9ecc418787"

[update]
[update.curseforge]
file-id = 3682815
project-id = 453925
