name = "Macaw's Roofs"
filename = "mcw-roofs-2.0.1-mc1.16.5-4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3182/364/mcw-roofs-2.0.1-mc1.16.5-4.jar"
hash-format = "sha1"
hash = "496c851ef6422603e914901a37b6e5c93a68850e"

[update]
[update.curseforge]
file-id = 3182364
project-id = 352039
