name = "Not Enough Animations"
filename = "notenoughanimations-forge-1.6.0-mc1.18.2.jar"
side = "client"

[download]
url = "https://nocturne705.github.io/notenoughanimations-forge-1.6.0-mc1.18.2.jar"
hash-format = "sha1"
hash = "D1D954139650BEFB005FFB11B608A571E728DB94"

[option]
optional = true
default = true
description = "Gives yourself and others more robust animations."