name = "Occultism"
filename = "occultism-1.16.5-1.24.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3589/995/occultism-1.16.5-1.24.0.jar"
hash-format = "sha1"
hash = "e2e5abc2d078974023bcdf2eeb1a29cfca508dbc"

[update]
[update.curseforge]
file-id = 3589995
project-id = 361026
