name = "Phi (Psi addon)"
filename = "Phi-1.16-2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/231/Phi-1.16-2.4.jar"
hash-format = "sha1"
hash = "e359c394c15a3798f251282ee36cb847b19280db"

[update]
[update.curseforge]
file-id = 3646231
project-id = 476728
