name = "Pokecube AIO"
filename = "pokecube-aio-1.16.5-3.14.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/594/pokecube-aio-1.16.5-3.14.1.jar"
hash-format = "sha1"
hash = "cde86183c9d75ef00ded4f56f8bfc731fe21641c"

[update]
[update.curseforge]
file-id = 3600594
project-id = 285121
