name = "Project Red - Integration"
filename = "ProjectRed-1.16.5-4.11.0-integration.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/375/ProjectRed-1.16.5-4.11.0-integration.jar"
hash-format = "sha1"
hash = "c5a5fd93c96b118d9805097ca9a9f3e7cc2ac3e9"

[update]
[update.curseforge]
file-id = 3639375
project-id = 229045
