name = "Project Red - Transmission"
filename = "ProjectRed-1.16.5-4.11.0-transmission.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/379/ProjectRed-1.16.5-4.11.0-transmission.jar"
hash-format = "sha1"
hash = "2f4a7f2844161914bb860464208a39fd5e27a5b7"

[update]
[update.curseforge]
file-id = 3639379
project-id = 478939
