name = "Project Red - Core"
filename = "ProjectRed-1.16.5-4.11.0-core.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/374/ProjectRed-1.16.5-4.11.0-core.jar"
hash-format = "sha1"
hash = "9b2e8de49d8a1657299565cb30ab194ec015aee7"

[update]
[update.curseforge]
file-id = 3639374
project-id = 228702
