name = "Project Red - Exploration"
filename = "ProjectRed-1.16.5-4.11.0-exploration.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/378/ProjectRed-1.16.5-4.11.0-exploration.jar"
hash-format = "sha1"
hash = "2efcb415222d2e2f080e7af5e6879efca7210657"

[update]
[update.curseforge]
file-id = 3639378
project-id = 229049
