name = "Simple Delights"
filename = "simpledelights-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3491/446/simpledelights-1.2.jar"
hash-format = "sha1"
hash = "f9c928a4fdedf6e53c6936659c8542934eb77b6c"

[update]
[update.curseforge]
file-id = 3491446
project-id = 513959
