name = "The Undergarden"
filename = "The_Undergarden-1.16.5-0.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3477/594/The_Undergarden-1.16.5-0.5.5.jar"
hash-format = "sha1"
hash = "829b00b7a6e1e4dce78497d3b0aff56dedf32055"

[update]
[update.curseforge]
file-id = 3477594
project-id = 379849
