name = "Titanium"
filename = "titanium-1.16.5-3.2.8.4-10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3346/366/titanium-1.16.5-3.2.8.4-10.jar"
hash-format = "sha1"
hash = "3e112eb4fb7f02837dff8dbdde2942bfe78bd3f8"

[update]
[update.curseforge]
file-id = 3346366
project-id = 287342
