name = "Werewolves - Become a Beast!"
filename = "Werewolves-1.18.2-1.8-0.6.1.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "d998fa7c1be8c3f442ed7f1b255dd82af1274d80"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3803356
project-id = 417851
